#!/usr/bin/env node
/**
 * Version & metadata manager.
 *
 * Bumps the package version (optional), writes src/version.ts, and regenerates
 * the SEO / LLM discovery files (robots.txt, sitemap.xml, llms.txt, llms-full.txt)
 * with the current version, date and site URL.
 *
 * Usage:
 *   node scripts/version.mjs            # regenerate files, keep current version
 *   node scripts/version.mjs patch      # 0.1.0 -> 0.1.1
 *   node scripts/version.mjs minor      # 0.1.0 -> 0.2.0
 *   node scripts/version.mjs major      # 0.1.0 -> 1.0.0
 *   node scripts/version.mjs 1.2.3      # set explicit version
 *
 * Configure the public site URL via the SITE_URL env var (default below).
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE_URL = (process.env.SITE_URL || "https://djdevpro.github.io/RagViewer").replace(/\/$/, "");
const APP_NAME = "RagViewer";

function bump(v, kind) {
  const [a, b, c] = v.split(".").map(Number);
  if (kind === "major") return `${a + 1}.0.0`;
  if (kind === "minor") return `${a}.${b + 1}.0`;
  if (kind === "patch") return `${a}.${b}.${c + 1}`;
  if (/^\d+\.\d+\.\d+$/.test(kind)) return kind;
  return v;
}

const pkgPath = join(ROOT, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const arg = process.argv[2];
const version = arg ? bump(pkg.version, arg) : pkg.version;
const date = new Date().toISOString().slice(0, 10);

if (arg && version !== pkg.version) {
  pkg.version = version;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
}

const write = (rel, content) => {
  const full = join(ROOT, rel);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
  console.log("wrote", rel);
};

// --- src/version.ts ---
write(
  "src/version.ts",
  `// Generated by scripts/version.mjs — do not edit by hand.\n` +
    `export const VERSION = "${version}";\n` +
    `export const BUILD_DATE = "${date}";\n`,
);

// --- robots.txt ---
write("public/robots.txt", `User-agent: *\nAllow: /\n\nSitemap: ${SITE_URL}/sitemap.xml\n`);

// --- sitemap.xml ---
const pages = ["/"];
write(
  "public/sitemap.xml",
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    pages
      .map(
        (p) =>
          `  <url><loc>${SITE_URL}${p}</loc><lastmod>${date}</lastmod><changefreq>monthly</changefreq><priority>1.0</priority></url>`,
      )
      .join("\n") +
    `\n</urlset>\n`,
);

// --- llms.txt (concise) ---
write(
  "public/llms.txt",
  `# ${APP_NAME}

> A 100% client-side web app that turns PDFs into a queryable knowledge base in the browser. It converts documents to DocLang (a structured XML format), chunks them, computes embeddings, lets you explore the embedding cloud, and answers questions over your documents with retrieval-augmented generation (RAG). Documents can stay entirely on-device.

Version: ${version} (${date})
Home: ${SITE_URL}/

## What it does
- Convert a PDF to DocLang in the browser (local headless engine) or via a docling-serve server.
- Chunk the document with 5 configurable strategies (structural, hybrid, recursive, fixed, semantic) and live preview.
- Embed chunks with Transformers.js (in-browser) or an Ollama model.
- Store vectors in EntityDB (local, IndexedDB) or a remote Qdrant server.
- Explore: an interactive embedding cloud + semantic search that re-ranks chunks by distance.
- Chat: streaming RAG answers (OpenAI or Ollama), with cited sources and conversation history.
- Versioned chunkings: snapshot multiple chunking configs and bind each conversation to one.

## Key facts
- Privacy: can run fully client-side and offline (installable PWA); no upload required.
- Embeddings: Transformers.js (e.g. Xenova/all-MiniLM-L6-v2) or Ollama.
- Vector DB: EntityDB (browser) or Qdrant (server).
- Chat LLM: OpenAI API or a local Ollama server.

## Links
- DocLang spec: https://github.com/doclang-project/doclang
- Docling: https://github.com/docling-project/docling
`,
);

// --- llms-full.txt (detailed) ---
write(
  "public/llms-full.txt",
  `# ${APP_NAME} — full description

Version: ${version} (${date})
Home: ${SITE_URL}/

## Summary
${APP_NAME} is a browser-based RAG (retrieval-augmented generation) workbench for
documents. It converts a PDF into DocLang — a structured XML representation of a
document's semantics, structure and geometry — then chunks, embeds, indexes,
explores and chats with it. It is designed so the whole pipeline can run on-device.

## Pipeline / workspace steps
1. Preview — render the original PDF pages and the converted DocLang as HTML / XML / Markdown.
2. Chunking — pick a strategy and tune size/structure/context/overlap; a live overlay
   shows exactly how the document is cut. Strategies: structural, hybrid, recursive,
   fixed, semantic. Presets are provided.
3. Explore — "Compute & explore" embeds the chunks and builds an interactive embedding
   cloud (k-NN force graph). A semantic search box highlights the nearest nodes and
   re-orders the chunk panel by distance (closest first).
4. Chat — ask questions; the app embeds the query, retrieves the nearest chunks from the
   conversation's vector index, and streams a grounded answer with cited, clickable
   sources. Markdown is rendered live.

## Conversion engines
- Local (headless): converts PDFs to DocLang fully in the browser.
- Server: a docling-serve instance (also handles images).

## Embeddings
- Transformers.js in-browser (default, e.g. Xenova/all-MiniLM-L6-v2).
- Ollama embedding models (e.g. an embedding model served by a local Ollama).

## Vector stores
- EntityDB: fully client-side, persisted in IndexedDB.
- Qdrant: a remote Qdrant server reached over its REST API (URL + API key).

## Chat providers
- OpenAI (API key), streaming.
- Ollama (local server), streaming.
The system prompt is editable in Settings.

## Versioned chunkings
Each "Compute & explore" creates a chunking version (a snapshot of the config, chunks,
embedding cloud and vector index). Versions appear as tiles; selecting a version drives
the Explore cloud and filters the chat conversation list. Every conversation is bound to
a specific version so the LLM always queries the matching RAG index.

## Privacy & offline
- Can run 100% client-side: documents never need to leave the device.
- Progressive Web App: installable; embedding model weights are cached after first load
  for offline use.

## Related
- DocLang specification: https://github.com/doclang-project/doclang
- Docling (document conversion): https://github.com/docling-project/docling
- Transformers.js: https://github.com/huggingface/transformers.js
- Ollama: https://ollama.com
- Qdrant: https://qdrant.tech
`,
);

console.log(`\n${APP_NAME} v${version} (${date}) — metadata regenerated. SITE_URL=${SITE_URL}`);
